### ISSUE TITLE
[charts/kelbi] lancherserver requires Service on Port 80

### ISSUE THREAD

**Issue by Tsugami** [Invasor-de-Fronteiras/helm-charts#1]
The Launcher Server needs to be configured to use the HTTPS protocol on port 80.

 Expected Output:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: launcherserver-svc 
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: MyApp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
 ```

## Requirements:
- The service template must be located in the `charts/kelbi/launcherserver` folder.
- The default service type should be `ClusterIP` but it should be customizable via Helm values.
- The Helm values for configuring the Launcher Server service should be defined under `launcherServer.service`.

Helm Values Example (values.yaml):
```yaml
launcherServer:
  service:
   enabled: true
    # Service type
    ##
    type: ClusterIP
```

## References:

[Old Service of Kelbi](https://github.com/Invasor-de-Fronteiras/helm-charts/commit/293cf3a658b22d356e2cd6d7595cf8ae9f0b7351#diff-5e0e4699e8e1727a9001721195d575fd735dfbdb49dfa7b6d5a8662a51201613R35-R36)
[Service Template of Prometheus Helm Chart](https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/templates/service.yaml)
